# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

import wutils
import os
import Options

def options(opt):
         (main.cc)

def build(bld):
    module = bld.create_ns3_module('dev-coop-sys', ['core'])
    module.source = [
        'util/util.cc',
        'model/clustering.cc',
        'model/neighbor.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'dev-coop-sys'
    headers.source = [
        'util/util.h',
        'model/clustering.h',
        'model/neighbor.h',
        ]

    # bld.ns3_python_bindings()
