# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('clustering', ['core', 'internet','wave', 'v2v'])
    module.source = [
        'model/cluster-control-client.cc',
        'model/cluster-sap.cc',
        'model/cluster-header.cc',
        'helper/cluster-control-client-helper.cc',
        'model/propagation-control-header.cc'
        ]

    headers = bld(features='ns3header')
    headers.module = 'clustering'
    headers.source = [
        'model/cluster-control-client.h',
        'model/cluster-header.h',
        'model/cluster-sap.h',
        'helper/cluster-control-client-helper.h',
        'model/propagation-control-header.h',
        'model/meta-data.h'
        ]

    # bld.ns3_python_bindings()
